void transCount(int *, int *, int *, double *, double *, double *, int *, double *, int *, double *);
void transProbs(int *, int *, double *, double *);
void wl(int *, int *, double *, double *, double *, int *);
void nsph(int *, double *, double *);
void cEmbedLen(int *, int *, double *, int *, int *, int *, double *, double *);
void cEmbedOc(int *, int *, int *, double *, int *, int *, int *, double *);
void cEmbedTrans(int *, int *, int *, int *, int *);
void embedTProbs(int *, double *);
void ellinter(int *, int *, double *, double *, double *);
void getDst(int *, int *, double *, double *, double *);
void fastMatProd(int *, int *, double *, int *, double *, double *);
void jointProbs(int *, int *, int *, double *, double *);
void tsimCate(int *, int *, double *, int *);
SEXP isOmp();
void getNumCores(int *);
void getNumSlaves(int *);
void setNumSlaves(int *);
void fastSVDprod(double *, double *, double *, int *);
SEXP annealingSIM(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP geneticSIM(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
void expmat(double *, int *, double *);
void predTPFIT(double *, double *, double *, int *, double *);
void nrmPrMat(double *, int *);
void revCoef(double *, double *, int *, double *);
void predVET(double *, double *, int *, int *, double *, double *);
void predMULTI(double *, double *, double *, int *, int *, int*, double *);
void wd(double *, int *, int *, int *);
void predPSEUDOVET(double *, double *, int *, int *, int *, double *, double *);
void predPSEUDO(double *, double *, double *, int *, int *, int *, int *, int *, int *, double *);
void rotaH(int *, double *, double *);
void jointProbsMCS(double *, int *, double *, int *, int *, int *, int *, double *, double *, int*, double *);
void rotaxes(int *, double *, double *);
void fastrss(int *, double *, double *, double *);
SEXP bclm(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
void knear(int *, int *, double *, int *, double *, int *, int *);
void getIKPrbs(int *, int *, int *, int *, int *, int *, int *, int *, double *, double *, int *, double *, double *, double *);
void getCKPrbs(int *, int *, int *, int *, int *, int *, int *, int *, double *, double *, int *, double *, double *, double *);
void KjointProbsMCS(double *, int *, double *, int *, int *, int *, int *, int *, double *, int *, double *);
void cEmbFrq(double *, int *, int *, double *, double *);
void pathAlg(int *, int *, int *, double *, double *, int *, double *, int *, int *, double *, double *, double *, int *);
void getPos(double *, int *, int *, int *, int *, int *);
void nearDire(int *, int *, double *, int *);
void objfun(int *, int *, int *, int *, double *, double *, double *, double *);
void fastobjfun(int *, int *, int *, int *, int *, int *, int *, double *, double *, double *, int *, double *, double *);
